spring:
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: gcp-demo
        instance-connection-name: gcp-demo-jesushenriquez:us-central1:gcp-demo-sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
    username: guest
    password: guest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect